---
   - hosts: vagrant-packer-centos7 
     tasks:

     - name: Create a started container
       lxc_container:
         name: test-container
         container_log: true
         template: centos
         state: started
         template_options: --release 7
       become: true
