---
   - hosts: vagrant-packer-centos7 
     tasks:

     - name: Create a started container
       lxc_container:
         name: test-container-started
         container_log: true
         template: lxc-centos 
         state: started
         template_options: --release trusty
