---
   - hosts: vagrant-packer-centos7 
     tasks:

     - user:
         name: forgerock 
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: .ssh/id_rsa
       become: true
